name: SoKrutoiPowersPlugin
version: 1.0
main: org.sokrutoi.soKrutoiPowersPlugin.SoKrutoiPowersPlugin
api-version: '1.21'
description: Супер-силы для сервера SoKrutoi


commands:
  givepower:
    description: Выдать суперсилу игроку
    usage: /givepower <игрок> <суперсила>
    permission: sokrutoi.givepower
    tab-complete: true
  clearpowers:
    description: Очистить суперсилы у игрока
    usage: /clearpowers <игрок|**>
    permission: sokrutoi.clearpowers
    tab-complete: true
  resetpowers:
    description: Сбросить активное состояние сил (кулдауны, невидимость, размер)
    usage: /resetpowers <игрок|**>
    permission: sokrutoi.resetpowers
    tab-complete: true
  whohaspowers:
    description: Показать у кого какие суперсилы
    usage: /whohaspowers
    permission: sokrutoi.whohaspowers
  setconfig:
    description: Изменить параметр конфига плагина в реальном времени
    usage: /setconfig <ключ> <значение>
    permission: sokrutoi.setconfig
    tab-complete: true
  randompowers:
    description: Случайно раздать суперсилы всем онлайн-игрокам
    usage: /randompowers [сила1] [сила2] ...
    permission: sokrutoi.randompowers
    tab-complete: true
  giveluckyarrow:
    description: Выдать Стрелу Судьбы игроку
    usage: /giveluckyarrow <игрок> [количество]
    permission: sokrutoi.giveluckyarrow
    tab-complete: true
  powers:
    description: Помощь по плагину суперсил
    usage: /powers

permissions:
  sokrutoi.givepower:
    description: Доступ к выдаче суперсил
    default: op
  sokrutoi.clearpowers:
    description: Доступ к очистке суперсил
    default: op
  sokrutoi.resetpowers:
    description: Доступ к сбросу состояния сил
    default: op
  sokrutoi.whohaspowers:
    description: Просмотр суперсил игроков
    default: op
  sokrutoi.setconfig:
    description: Изменение конфига плагина в игре
    default: op
  sokrutoi.randompowers:
    description: Случайная раздача суперсил
    default: op
  sokrutoi.giveluckyarrow:
    description: Выдача Стрелы Судьбы
    default: op